export interface CityDetail {
  name: string;
  latitude: string;
  longitude: string;
}

export const CITY_DETAILS: CityDetail[] = [
  { name: "Virar", latitude: "19.4541", longitude: "72.8101" },
  { name: "Nalasopara", latitude: "19.4179", longitude: "72.8186" },
  { name: "Vasai Road", latitude: "19.3812", longitude: "72.8229" },
  { name: "Naigaon", latitude: "19.3364", longitude: "72.8358" },
  { name: "Bhayandar", latitude: "19.3005", longitude: "72.8502" },
  { name: "Mira Road", latitude: "19.2812", longitude: "72.8550" },
  { name: "Dahisar", latitude: "19.2504", longitude: "72.8587" },
  { name: "Borivali", latitude: "19.2307", longitude: "72.8567" },
  { name: "Kandivali", latitude: "19.2066", longitude: "72.8510" },
  { name: "Malad", latitude: "19.1860", longitude: "72.8483" },
  { name: "Goregaon", latitude: "19.1646", longitude: "72.8493" },
  { name: "Jogeshwari", latitude: "19.1353", longitude: "72.8490" },
  { name: "Andheri", latitude: "19.1197", longitude: "72.8464" },
  { name: "Vile Parle", latitude: "19.1018", longitude: "72.8450" },
  { name: "Santacruz", latitude: "19.0833", longitude: "72.8431" },
  { name: "Khar Road", latitude: "19.0680", longitude: "72.8415" },
  { name: "Bandra", latitude: "19.0543", longitude: "72.8402" },
  { name: "Mahim", latitude: "19.0402", longitude: "72.8422" },
  { name: "Matunga Road", latitude: "19.0270", longitude: "72.8438" },
  { name: "Dadar", latitude: "19.0181", longitude: "72.8447" },
  { name: "Prabhadevi", latitude: "19.0120", longitude: "72.8432" },
  { name: "Lower Parel", latitude: "18.9984", longitude: "72.8315" },
  { name: "Mahalaxmi", latitude: "18.9850", longitude: "72.8258" },
  { name: "Mumbai Central", latitude: "18.9697", longitude: "72.8194" },
  { name: "Grant Road", latitude: "18.9598", longitude: "72.8157" },
  { name: "Charni Road", latitude: "18.9497", longitude: "72.8222" },
  { name: "Marine Lines", latitude: "18.9441", longitude: "72.8255" },
  { name: "Churchgate", latitude: "18.9322", longitude: "72.8264" },




  { name: "Chhatrapati Shivaji Maharaj Terminus", latitude: "18.9398", longitude: "72.8355" },
  { name: "Masjid", latitude: "18.9515", longitude: "72.8381" },
  { name: "Sandhurst Road", latitude: "18.9615", longitude: "72.8398" },
  { name: "Byculla", "latitude": "18.9754", "longitude": "72.8327" },
  { name: "Chinchpokli", latitude: "18.9868", longitude: "72.8315" },
  { name: "Currey Road", latitude: "18.9942", longitude: "72.8331" },
  { name: "Parel", latitude: "19.0092", longitude: "72.8364" },
  { name: "Dadar", latitude: "19.0181", longitude: "72.8447" },
  { name: "Matunga", latitude: "19.0270", longitude: "72.8498" },
  { name: "Sion", latitude: "19.0392", longitude: "72.8595" },
  { name: "Kurla", latitude: "19.0652", longitude: "72.8794" },
  { name: "Vidyavihar", latitude: "19.0797", longitude: "72.8687" },
  { name: "Ghatkopar", latitude: "19.0865", longitude: "72.8665" },
  { name: "Vikhroli", latitude: "19.1112", longitude: "72.9248" },
  { name: "Kanjurmarg", latitude: "19.1314", longitude: "72.9351" },
  { name: "Bhandup", latitude: "19.1450", longitude: "72.9366" },
  { name: "Nahur", latitude: "19.1543", longitude: "72.9411" },
  { name: "Mulund", latitude: "19.1726", longitude: "72.9564" },
  { name: "Thane", latitude: "19.1860", longitude: "72.9759" },
  { name: "Kalva", latitude: "19.2012", longitude: "72.9934" },
  { name: "Mumbra", latitude: "19.1906", longitude: "73.0228" },
  { name: "Diva", latitude: "19.1884", longitude: "73.0425" },
  { name: "Koppar", latitude: "19.2133", longitude: "73.0769" },
  { name: "Dombivli", latitude: "19.2184", longitude: "73.0868" },
  { name: "Thakurli", latitude: "19.2238", longitude: "73.0991" },
  { name: "Kalyan", latitude: "19.2364", longitude: "73.1300" },




  { name: "Chhatrapati Shivaji Maharaj Terminus", latitude: "18.9398", longitude: "72.8355" },
  { name: "Masjid", latitude: "18.9515", longitude: "72.8381" },
  { name: "Sandhurst Road", latitude: "18.9615", longitude: "72.8398" },
  { name: "Dockyard Road", latitude: "18.9667", longitude: "72.8436" },
  { name: "Reay Road", latitude: "18.9822", longitude: "72.8435" },
  { name: "Cotton Green", latitude: "18.9866", longitude: "72.8428" },
  { name: "Sewri", latitude: "19.0001", longitude: "72.8554" },
  { name: "Vadala Road", latitude: "19.0215", longitude: "72.8567" },
  
  // Navi Mumbai / Panvel Branch
  { name: "Guru Tegh Bahadur Nagar", latitude: "19.0366", longitude: "72.8659" },
  { name: "Chunabhatti", latitude: "19.0494", longitude: "72.8698" },
  { name: "Kurla", latitude: "19.0652", longitude: "72.8794" },
  { name: "Tilak Nagar", latitude: "19.0664", longitude: "72.8942" },
  { name: "Chembur", latitude: "19.0624", longitude: "72.9015" },
  { name: "Govandi", latitude: "19.0553", longitude: "72.9152" },
  { name: "Mankhurd", latitude: "19.0505", longitude: "72.9320" },
  { name: "Vashi", latitude: "19.0644", longitude: "72.9991" },
  { name: "Sanpada", "latitude": "19.0628", "longitude": "73.0169" },
  { name: "Juinagar", latitude: "19.0544", longitude: "73.0294" },
  { name: "Nerul", latitude: "19.0336", longitude: "73.0178" },
  { name: "Seawoods–Darave", latitude: "19.0217", longitude: "73.0189" },
  { name: "Belapur CBD", latitude: "19.0186", longitude: "73.0396" },
  { name: "Kharghar", latitude: "19.0247", longitude: "73.0649" },
  { name: "Mansarovar", latitude: "19.0232", longitude: "73.0841" },
  { name: "Khandeshwar", latitude: "19.0219", longitude: "73.1041" },
  { name: "Panvel", latitude: "18.9894", longitude: "73.1214" },

  // Western Branch Extension from Vadala Road
  { name: "King's Circle", latitude: "19.0322", longitude: "72.8559" },
  { name: "Mahim", latitude: "19.0402", longitude: "72.8422" },
  { name: "Bandra", latitude: "19.0543", longitude: "72.8402" },
  { name: "Khar Road", latitude: "19.0680", longitude: "72.8415" },
  { name: "Santacruz", latitude: "19.0833", longitude: "72.8431" },
  { name: "Vile Parle", latitude: "19.1018", longitude: "72.8450" },
  { name: "Andheri", latitude: "19.1197", longitude: "72.8464" },
  { name: "Jogeshwari", latitude: "19.1353", longitude: "72.8490" },
  { name: "Ram Mandir", latitude: "19.1512", longitude: "72.8491" },
  { name: "Goregaon", latitude: "19.1646", longitude: "72.8493" },



  
  { name: "Mumbai", latitude: "", longitude: "" },
  { name: "South Mumbai", latitude: "", longitude: "" },
  { name: "Colaba", latitude: "", longitude: "" },
  { name: "Nariman Point", latitude: "", longitude: "" },
  { name: "Churchgate", latitude: "", longitude: "" },
  { name: "Marine Lines", latitude: "", longitude: "" },
  { name: "Charni Road", latitude: "", longitude: "" },
  { name: "Grant Road", latitude: "", longitude: "" },
  { name: "Mumbai Central", latitude: "", longitude: "" },
  { name: "Byculla", latitude: "", longitude: "" },
  { name: "Masjid", latitude: "", longitude: "" },
  { name: "Sandhurst Road", latitude: "", longitude: "" },
  { name: "Dadar", latitude: "", longitude: "" },
  { name: "Matunga", latitude: "", longitude: "" },
  { name: "Sion", latitude: "", longitude: "" },
  { name: "Wadala", latitude: "", longitude: "" },
  { name: "Parel", latitude: "", longitude: "" },
  { name: "Lower Parel", latitude: "", longitude: "" },
  { name: "Worli", latitude: "", longitude: "" },
  { name: "Prabhadevi", latitude: "", longitude: "" },
  { name: "Mahim", latitude: "", longitude: "" },
  { name: "Bandra", latitude: "", longitude: "" },
  { name: "Khar", latitude: "", longitude: "" },
  { name: "Santacruz", latitude: "", longitude: "" },
  { name: "Vile Parle", latitude: "", longitude: "" },
  { name: "Andheri", latitude: "", longitude: "" },
  { name: "Jogeshwari", latitude: "", longitude: "" },
  { name: "Goregaon", latitude: "", longitude: "" },
  { name: "Malad", latitude: "", longitude: "" },
  { name: "Kandivali", latitude: "", longitude: "" },
  { name: "Borivali", latitude: "", longitude: "" },
  { name: "Dahisar", latitude: "", longitude: "" },
  { name: "Mira Road", latitude: "", longitude: "" },
  { name: "Bhayandar", latitude: "", longitude: "" },
  { name: "Bhayander", latitude: "", longitude: "" },
  { name: "Naigaon", latitude: "", longitude: "" },
  { name: "Vasai", latitude: "", longitude: "" },
  { name: "Virar", latitude: "", longitude: "" },
  { name: "Nalasopara", latitude: "", longitude: "" },
  { name: "Kurla", latitude: "", longitude: "" },
  { name: "Ghatkopar", latitude: "", longitude: "" },
  { name: "Vidyavihar", latitude: "", longitude: "" },
  { name: "Vikhroli", latitude: "", longitude: "" },
  { name: "Powai", latitude: "", longitude: "" },
  { name: "Bhandup", latitude: "", longitude: "" },
  { name: "Kanjurmarg", latitude: "", longitude: "" },
  { name: "Mulund", latitude: "", longitude: "" },
  { name: "Thane", latitude: "", longitude: "" },
  { name: "Chembur", latitude: "", longitude: "" },
  { name: "Trombay", latitude: "", longitude: "" },
  { name: "Govandi", latitude: "", longitude: "" },
  { name: "Mankhurd", latitude: "", longitude: "" },
  { name: "Deonar", latitude: "", longitude: "" },
  { name: "Turbhe", latitude: "", longitude: "" },
  { name: "Kopar Khairane", latitude: "", longitude: "" },
  { name: "Ghansoli", latitude: "", longitude: "" },
  { name: "Airoli", latitude: "", longitude: "" },
  { name: "Rabale", latitude: "", longitude: "" },
  { name: "Mahape", latitude: "", longitude: "" },
  { name: "Sanpada", latitude: "", longitude: "" },
  { name: "Vashi", latitude: "", longitude: "" },
  { name: "Nerul", latitude: "", longitude: "" },
  { name: "Belapur", latitude: "", longitude: "" },
  { name: "Kharghar", latitude: "", longitude: "" },
  { name: "Kamothe", latitude: "", longitude: "" },
  { name: "Kalamboli", latitude: "", longitude: "" },
  { name: "Panvel", latitude: "", longitude: "" },
  { name: "Taloja", latitude: "", longitude: "" },
  { name: "Seawoods", latitude: "", longitude: "" },
  { name: "Juinagar", latitude: "", longitude: "" },
  { name: "CBD Belapur", latitude: "", longitude: "" },
  { name: "Ulwe", latitude: "", longitude: "" },
  { name: "Dronagiri", latitude: "", longitude: "" },
  { name: "Jawaharlal Nehru Port", latitude: "", longitude: "" },
  { name: "Navi Mumbai", latitude: "", longitude: "" },
  { name: "Bhiwandi", latitude: "", longitude: "" },
  { name: "Kalyan", latitude: "", longitude: "" },
  { name: "Dombivli", latitude: "", longitude: "" },
  { name: "Ulhasnagar", latitude: "", longitude: "" },
  { name: "Ambarnath", latitude: "", longitude: "" },
  { name: "Badlapur", latitude: "", longitude: "" },
  { name: "Ambernath", latitude: "", longitude: "" },
  { name: "Shahapur", latitude: "", longitude: "" },
  { name: "Murbad", latitude: "", longitude: "" },
  { name: "Wada", latitude: "", longitude: "" },
  { name: "Palghar", latitude: "", longitude: "" },
  { name: "Dahanu", latitude: "", longitude: "" },
  { name: "Jawhar", latitude: "", longitude: "" },
  { name: "Mokhada", latitude: "", longitude: "" },
  { name: "Talasari", latitude: "", longitude: "" },
  { name: "Vada", latitude: "", longitude: "" },
  { name: "Delhi", latitude: "", longitude: "" },
  { name: "New Delhi", latitude: "", longitude: "" },
  { name: "North Delhi", latitude: "", longitude: "" },
  { name: "South Delhi", latitude: "", longitude: "" },
  { name: "East Delhi", latitude: "", longitude: "" },
  { name: "West Delhi", latitude: "", longitude: "" },
  { name: "Central Delhi", latitude: "", longitude: "" },
  { name: "North East Delhi", latitude: "", longitude: "" },
  { name: "North West Delhi", latitude: "", longitude: "" },
  { name: "South East Delhi", latitude: "", longitude: "" },
  { name: "South West Delhi", latitude: "", longitude: "" },
  { name: "Shahdara", latitude: "", longitude: "" },
  { name: "Dwarka", latitude: "", longitude: "" },
  { name: "Rohini", latitude: "", longitude: "" },
  { name: "Pitampura", latitude: "", longitude: "" },
  { name: "Janakpuri", latitude: "", longitude: "" },
  { name: "Rajouri Garden", latitude: "", longitude: "" },
  { name: "Lajpat Nagar", latitude: "", longitude: "" },
  { name: "Greater Kailash", latitude: "", longitude: "" },
  { name: "Saket", latitude: "", longitude: "" },
  { name: "Vasant Kunj", latitude: "", longitude: "" },
  { name: "Connaught Place", latitude: "", longitude: "" },
  { name: "Karol Bagh", latitude: "", longitude: "" },
  { name: "Chandni Chowk", latitude: "", longitude: "" },
  { name: "Daryaganj", latitude: "", longitude: "" },
  { name: "Preet Vihar", latitude: "", longitude: "" },
  { name: "Mayur Vihar", latitude: "", longitude: "" },
  { name: "Laxmi Nagar", latitude: "", longitude: "" },
  { name: "Noida", latitude: "", longitude: "" },
  { name: "Greater Noida", latitude: "", longitude: "" },
  { name: "Ghaziabad", latitude: "", longitude: "" },
  { name: "Faridabad", latitude: "", longitude: "" },
  { name: "Gurgaon", latitude: "", longitude: "" },
  { name: "Gurugram", latitude: "", longitude: "" },
  { name: "Bahadurgarh", latitude: "", longitude: "" },
  { name: "Ballabgarh", latitude: "", longitude: "" },
  { name: "Palwal", latitude: "", longitude: "" },
  { name: "Manesar", latitude: "", longitude: "" },
  { name: "Sohna", latitude: "", longitude: "" },
  { name: "Bangalore", latitude: "", longitude: "" },
  { name: "Bengaluru", latitude: "", longitude: "" },
  { name: "Whitefield", latitude: "", longitude: "" },
  { name: "Electronic City", latitude: "", longitude: "" },
  { name: "Koramangala", latitude: "", longitude: "" },
  { name: "HSR Layout", latitude: "", longitude: "" },
  { name: "Indiranagar", latitude: "", longitude: "" },
  { name: "Jayanagar", latitude: "", longitude: "" },
  { name: "JP Nagar", latitude: "", longitude: "" },
  { name: "Bannerghatta Road", latitude: "", longitude: "" },
  { name: "Marathahalli", latitude: "", longitude: "" },
  { name: "MG Road", latitude: "", longitude: "" },
  { name: "Rajajinagar", latitude: "", longitude: "" },
  { name: "Malleshwaram", latitude: "", longitude: "" },
  { name: "Basavanagudi", latitude: "", longitude: "" },
  { name: "BTM Layout", latitude: "", longitude: "" },
  { name: "Yelahanka", latitude: "", longitude: "" },
  { name: "Hebbal", latitude: "", longitude: "" },
  { name: "Nagawara", latitude: "", longitude: "" },
  { name: "Kalyan Nagar", latitude: "", longitude: "" },
  { name: "KR Puram", latitude: "", longitude: "" },
  { name: "Hyderabad", latitude: "", longitude: "" },
  { name: "Secunderabad", latitude: "", longitude: "" },
  { name: "Gachibowli", latitude: "", longitude: "" },
  { name: "Hitech City", latitude: "", longitude: "" },
  { name: "Kondapur", latitude: "", longitude: "" },
  { name: "Madhapur", latitude: "", longitude: "" },
  { name: "Banjara Hills", latitude: "", longitude: "" },
  { name: "Jubilee Hills", latitude: "", longitude: "" },
  { name: "Kukatpally", latitude: "", longitude: "" },
  { name: "Ameerpet", latitude: "", longitude: "" },
  { name: "Begumpet", latitude: "", longitude: "" },
  { name: "LB Nagar", latitude: "", longitude: "" },
  { name: "Uppal", latitude: "", longitude: "" },
  { name: "Malkajgiri", latitude: "", longitude: "" },
  { name: "Tarnaka", latitude: "", longitude: "" },
  { name: "Chennai", latitude: "", longitude: "" },
  { name: "Anna Nagar", latitude: "", longitude: "" },
  { name: "T Nagar", latitude: "", longitude: "" },
  { name: "Adyar", latitude: "", longitude: "" },
  { name: "Velachery", latitude: "", longitude: "" },
  { name: "OMR", latitude: "", longitude: "" },
  { name: "Porur", latitude: "", longitude: "" },
  { name: "Ambattur", latitude: "", longitude: "" },
  { name: "Avadi", latitude: "", longitude: "" },
  { name: "Pallavaram", latitude: "", longitude: "" },
  { name: "Chromepet", latitude: "", longitude: "" },
  { name: "Tambaram", latitude: "", longitude: "" },
  { name: "Medavakkam", latitude: "", longitude: "" },
  { name: "Sholinganallur", latitude: "", longitude: "" },
  { name: "Perungudi", latitude: "", longitude: "" },
  { name: "Guindy", latitude: "", longitude: "" },
  { name: "Kodambakkam", latitude: "", longitude: "" },
  { name: "Egmore", latitude: "", longitude: "" },
  { name: "Mylapore", latitude: "", longitude: "" },
  { name: "Nungambakkam", latitude: "", longitude: "" },
  { name: "Royapettah", latitude: "", longitude: "" },
  { name: "Kolkata", latitude: "", longitude: "" },
  { name: "Howrah", latitude: "", longitude: "" },
  { name: "Salt Lake", latitude: "", longitude: "" },
  { name: "Bidhannagar", latitude: "", longitude: "" },
  { name: "New Town", latitude: "", longitude: "" },
  { name: "Rajarhat", latitude: "", longitude: "" },
  { name: "Park Street", latitude: "", longitude: "" },
  { name: "Ballygunge", latitude: "", longitude: "" },
  { name: "Jadavpur", latitude: "", longitude: "" },
  { name: "Garia", latitude: "", longitude: "" },
  { name: "Behala", latitude: "", longitude: "" },
  { name: "Barasat", latitude: "", longitude: "" },
  { name: "Barrackpore", latitude: "", longitude: "" },
  { name: "Dum Dum", latitude: "", longitude: "" },
  { name: "Serampore", latitude: "", longitude: "" },
  { name: "Chandannagar", latitude: "", longitude: "" },
  { name: "Kalyani", latitude: "", longitude: "" },
  { name: "Pune", latitude: "", longitude: "" },
  { name: "Hinjewadi", latitude: "", longitude: "" },
  { name: "Kharadi", latitude: "", longitude: "" },
  { name: "Viman Nagar", latitude: "", longitude: "" },
  { name: "Koregaon Park", latitude: "", longitude: "" },
  { name: "Kalyani Nagar", latitude: "", longitude: "" },
  { name: "Magarpatta", latitude: "", longitude: "" },
  { name: "Aundh", latitude: "", longitude: "" },
  { name: "Baner", latitude: "", longitude: "" },
  { name: "Wakad", latitude: "", longitude: "" },
  { name: "Pimple Saudagar", latitude: "", longitude: "" },
  { name: "Pimpri", latitude: "", longitude: "" },
  { name: "Chinchwad", latitude: "", longitude: "" },
  { name: "Hadapsar", latitude: "", longitude: "" },
  { name: "Kondhwa", latitude: "", longitude: "" },
  { name: "Kothrud", latitude: "", longitude: "" },
  { name: "Deccan", latitude: "", longitude: "" },
  { name: "Shivajinagar", latitude: "", longitude: "" },
  { name: "Camp", latitude: "", longitude: "" },
  { name: "Sinhagad Road", latitude: "", longitude: "" },
  { name: "Warje", latitude: "", longitude: "" },
  { name: "Bavdhan", latitude: "", longitude: "" },
  { name: "Sus", latitude: "", longitude: "" },
  { name: "Wagholi", latitude: "", longitude: "" },
  { name: "Manjri", latitude: "", longitude: "" },
  { name: "Saswad", latitude: "", longitude: "" },
  { name: "Ahmedabad", latitude: "", longitude: "" },
  { name: "Gandhinagar", latitude: "", longitude: "" },
  { name: "Satellite", latitude: "", longitude: "" },
  { name: "Bodakdev", latitude: "", longitude: "" },
  { name: "Vastrapur", latitude: "", longitude: "" },
  { name: "Navrangpura", latitude: "", longitude: "" },
  { name: "Maninagar", latitude: "", longitude: "" },
  { name: "Bopal", latitude: "", longitude: "" },
  { name: "Prahlad Nagar", latitude: "", longitude: "" },
  { name: "SG Highway", latitude: "", longitude: "" },
  { name: "Thaltej", latitude: "", longitude: "" },
  { name: "Sarkhej", latitude: "", longitude: "" },
  { name: "Chandkheda", latitude: "", longitude: "" },
  { name: "Gota", latitude: "", longitude: "" },
  { name: "Nikol", latitude: "", longitude: "" },
  { name: "Odhav", latitude: "", longitude: "" },
  { name: "Naroda", latitude: "", longitude: "" },
  { name: "Isanpur", latitude: "", longitude: "" },
  { name: "Vasna", latitude: "", longitude: "" },
  { name: "Memnagar", latitude: "", longitude: "" },
  { name: "Surat", latitude: "", longitude: "" },
  { name: "Adajan", latitude: "", longitude: "" },
  { name: "Rander", latitude: "", longitude: "" },
  { name: "Vesu", latitude: "", longitude: "" },
  { name: "Piplod", latitude: "", longitude: "" },
  { name: "Varachha", latitude: "", longitude: "" },
  { name: "Katargam", latitude: "", longitude: "" },
  { name: "Udhana", latitude: "", longitude: "" },
  { name: "Sarthana", latitude: "", longitude: "" },
  { name: "Athwa", latitude: "", longitude: "" },
  { name: "Dumas", latitude: "", longitude: "" },
  { name: "City Light", latitude: "", longitude: "" },
  { name: "Palanpur", latitude: "", longitude: "" },
  { name: "Vadodara", latitude: "", longitude: "" },
  { name: "Alkapuri", latitude: "", longitude: "" },
  { name: "Fatehgunj", latitude: "", longitude: "" },
  { name: "Gorwa", latitude: "", longitude: "" },
  { name: "Gotri", latitude: "", longitude: "" },
  { name: "Manjalpur", latitude: "", longitude: "" },
  { name: "Nizampura", latitude: "", longitude: "" },
  { name: "Sama", latitude: "", longitude: "" },
  { name: "Tarsali", latitude: "", longitude: "" },
  { name: "Waghodia", latitude: "", longitude: "" },
  { name: "Padra", latitude: "", longitude: "" },
  { name: "Rajkot", latitude: "", longitude: "" },
  { name: "Jamnagar", latitude: "", longitude: "" },
  { name: "Bhavnagar", latitude: "", longitude: "" },
  { name: "Gandhidham", latitude: "", longitude: "" },
  { name: "Morbi", latitude: "", longitude: "" },
  { name: "Junagadh", latitude: "", longitude: "" },
  { name: "Porbandar", latitude: "", longitude: "" },
  { name: "Surendranagar", latitude: "", longitude: "" },
  { name: "Anand", latitude: "", longitude: "" },
  { name: "Nadiad", latitude: "", longitude: "" },
  { name: "Bharuch", latitude: "", longitude: "" },
  { name: "Ankleshwar", latitude: "", longitude: "" },
  { name: "Valsad", latitude: "", longitude: "" },
  { name: "Vapi", latitude: "", longitude: "" },
  { name: "Navsari", latitude: "", longitude: "" },
  { name: "Jaipur", latitude: "", longitude: "" },
  { name: "Jodhpur", latitude: "", longitude: "" },
  { name: "Udaipur", latitude: "", longitude: "" },
  { name: "Kota", latitude: "", longitude: "" },
  { name: "Ajmer", latitude: "", longitude: "" },
  { name: "Bikaner", latitude: "", longitude: "" },
  { name: "Alwar", latitude: "", longitude: "" },
  { name: "Bharatpur", latitude: "", longitude: "" },
  { name: "Sikar", latitude: "", longitude: "" },
  { name: "Pali", latitude: "", longitude: "" },
  { name: "Tonk", latitude: "", longitude: "" },
  { name: "Jhunjhunu", latitude: "", longitude: "" },
  { name: "Churu", latitude: "", longitude: "" },
  { name: "Ganganagar", latitude: "", longitude: "" },
  { name: "Hanumangarh", latitude: "", longitude: "" },
  { name: "Bhilwara", latitude: "", longitude: "" },
  { name: "Nagaur", latitude: "", longitude: "" },
  { name: "Lucknow", latitude: "", longitude: "" },
  { name: "Kanpur", latitude: "", longitude: "" },
  { name: "Varanasi", latitude: "", longitude: "" },
  { name: "Allahabad", latitude: "", longitude: "" },
  { name: "Prayagraj", latitude: "", longitude: "" },
  { name: "Agra", latitude: "", longitude: "" },
  { name: "Meerut", latitude: "", longitude: "" },
  { name: "Bareilly", latitude: "", longitude: "" },
  { name: "Aligarh", latitude: "", longitude: "" },
  { name: "Gorakhpur", latitude: "", longitude: "" },
  { name: "Saharanpur", latitude: "", longitude: "" },
  { name: "Muzaffarnagar", latitude: "", longitude: "" },
  { name: "Mathura", latitude: "", longitude: "" },
  { name: "Firozabad", latitude: "", longitude: "" },
  { name: "Jhansi", latitude: "", longitude: "" },
  { name: "Moradabad", latitude: "", longitude: "" },
  { name: "Faizabad", latitude: "", longitude: "" },
  { name: "Ayodhya", latitude: "", longitude: "" },
  { name: "Chandigarh", latitude: "", longitude: "" },
  { name: "Mohali", latitude: "", longitude: "" },
  { name: "Panchkula", latitude: "", longitude: "" },
  { name: "Ludhiana", latitude: "", longitude: "" },
  { name: "Amritsar", latitude: "", longitude: "" },
  { name: "Jalandhar", latitude: "", longitude: "" },
  { name: "Patiala", latitude: "", longitude: "" },
  { name: "Bathinda", latitude: "", longitude: "" },
  { name: "Pathankot", latitude: "", longitude: "" },
  { name: "Hoshiarpur", latitude: "", longitude: "" },
  { name: "Firozpur", latitude: "", longitude: "" },
  { name: "Moga", latitude: "", longitude: "" },
  { name: "Sangrur", latitude: "", longitude: "" },
  { name: "Barnala", latitude: "", longitude: "" },
  { name: "Fazilka", latitude: "", longitude: "" },
  { name: "Gurdaspur", latitude: "", longitude: "" },
  { name: "Kapurthala", latitude: "", longitude: "" },
  { name: "Ropar", latitude: "", longitude: "" },
  { name: "Faridkot", latitude: "", longitude: "" },
  { name: "Malerkotla", latitude: "", longitude: "" },
  { name: "Ambala", latitude: "", longitude: "" },
  { name: "Karnal", latitude: "", longitude: "" },
  { name: "Panipat", latitude: "", longitude: "" },
  { name: "Hisar", latitude: "", longitude: "" },
  { name: "Rohtak", latitude: "", longitude: "" },
  { name: "Sonipat", latitude: "", longitude: "" },
  { name: "Yamunanagar", latitude: "", longitude: "" },
  { name: "Sirsa", latitude: "", longitude: "" },
  { name: "Bhiwani", latitude: "", longitude: "" },
  { name: "Jind", latitude: "", longitude: "" },
  { name: "Kaithal", latitude: "", longitude: "" },
  { name: "Kurukshetra", latitude: "", longitude: "" },
  { name: "Rewari", latitude: "", longitude: "" },
  { name: "Mahendragarh", latitude: "", longitude: "" },
  { name: "Fatehabad", latitude: "", longitude: "" },
  { name: "Shimla", latitude: "", longitude: "" },
  { name: "Manali", latitude: "", longitude: "" },
  { name: "Dharamshala", latitude: "", longitude: "" },
  { name: "Kullu", latitude: "", longitude: "" },
  { name: "Mandi", latitude: "", longitude: "" },
  { name: "Solan", latitude: "", longitude: "" },
  { name: "Kangra", latitude: "", longitude: "" },
  { name: "Hamirpur", latitude: "", longitude: "" },
  { name: "Una", latitude: "", longitude: "" },
  { name: "Bilaspur", latitude: "", longitude: "" },
  { name: "Chamba", latitude: "", longitude: "" },
  { name: "Kinnaur", latitude: "", longitude: "" },
  { name: "Lahaul", latitude: "", longitude: "" },
  { name: "Spiti", latitude: "", longitude: "" },
  { name: "Dehradun", latitude: "", longitude: "" },
  { name: "Haridwar", latitude: "", longitude: "" },
  { name: "Rishikesh", latitude: "", longitude: "" },
  { name: "Nainital", latitude: "", longitude: "" },
  { name: "Mussoorie", latitude: "", longitude: "" },
  { name: "Haldwani", latitude: "", longitude: "" },
  { name: "Roorkee", latitude: "", longitude: "" },
  { name: "Kashipur", latitude: "", longitude: "" },
  { name: "Rudrapur", latitude: "", longitude: "" },
  { name: "Pithoragarh", latitude: "", longitude: "" },
  { name: "Almora", latitude: "", longitude: "" },
  { name: "Ranikhet", latitude: "", longitude: "" },
  { name: "Tehri", latitude: "", longitude: "" },
  { name: "Pauri", latitude: "", longitude: "" },
  { name: "Chamoli", latitude: "", longitude: "" },
  { name: "Uttarkashi", latitude: "", longitude: "" },
  { name: "Bhopal", latitude: "", longitude: "" },
  { name: "Indore", latitude: "", longitude: "" },
  { name: "Gwalior", latitude: "", longitude: "" },
  { name: "Jabalpur", latitude: "", longitude: "" },
  { name: "Ujjain", latitude: "", longitude: "" },
  { name: "Sagar", latitude: "", longitude: "" },
  { name: "Dewas", latitude: "", longitude: "" },
  { name: "Satna", latitude: "", longitude: "" },
  { name: "Ratlam", latitude: "", longitude: "" },
  { name: "Rewa", latitude: "", longitude: "" },
  { name: "Murwara", latitude: "", longitude: "" },
  { name: "Singrauli", latitude: "", longitude: "" },
  { name: "Burhanpur", latitude: "", longitude: "" },
  { name: "Khandwa", latitude: "", longitude: "" },
  { name: "Bhind", latitude: "", longitude: "" },
  { name: "Chhindwara", latitude: "", longitude: "" },
  { name: "Guna", latitude: "", longitude: "" },
  { name: "Shivpuri", latitude: "", longitude: "" },
  { name: "Vidisha", latitude: "", longitude: "" },
  { name: "Chhatarpur", latitude: "", longitude: "" },
  { name: "Mandsaur", latitude: "", longitude: "" },
  { name: "Khargone", latitude: "", longitude: "" },
  { name: "Neemuch", latitude: "", longitude: "" },
  { name: "Pithampur", latitude: "", longitude: "" },
  { name: "Hoshangabad", latitude: "", longitude: "" },
  { name: "Itarsi", latitude: "", longitude: "" },
  { name: "Sehore", latitude: "", longitude: "" },
  { name: "Betul", latitude: "", longitude: "" },
  { name: "Morena", latitude: "", longitude: "" },
  { name: "Sheopur", latitude: "", longitude: "" },
  { name: "Raipur", latitude: "", longitude: "" },
  { name: "Bhilai", latitude: "", longitude: "" },
  { name: "Durg", latitude: "", longitude: "" },
  { name: "Korba", latitude: "", longitude: "" },
  { name: "Jagdalpur", latitude: "", longitude: "" },
  { name: "Raigarh", latitude: "", longitude: "" },
  { name: "Ambikapur", latitude: "", longitude: "" },
  { name: "Rajnandgaon", latitude: "", longitude: "" },
  { name: "Dhamtari", latitude: "", longitude: "" },
  { name: "Mahasamund", latitude: "", longitude: "" },
  { name: "Bhubaneswar", latitude: "", longitude: "" },
  { name: "Cuttack", latitude: "", longitude: "" },
  { name: "Rourkela", latitude: "", longitude: "" },
  { name: "Berhampur", latitude: "", longitude: "" },
  { name: "Sambalpur", latitude: "", longitude: "" },
  { name: "Puri", latitude: "", longitude: "" },
  { name: "Balasore", latitude: "", longitude: "" },
  { name: "Bhadrak", latitude: "", longitude: "" },
  { name: "Baripada", latitude: "", longitude: "" },
  { name: "Jharsuguda", latitude: "", longitude: "" },
  { name: "Jeypore", latitude: "", longitude: "" },
  { name: "Angul", latitude: "", longitude: "" },
  { name: "Dhenkanal", latitude: "", longitude: "" },
  { name: "Keonjhar", latitude: "", longitude: "" },
  { name: "Koraput", latitude: "", longitude: "" },
  { name: "Rayagada", latitude: "", longitude: "" },
  { name: "Bargarh", latitude: "", longitude: "" },
  { name: "Siliguri", latitude: "", longitude: "" },
  { name: "Durgapur", latitude: "", longitude: "" },
  { name: "Asansol", latitude: "", longitude: "" },
  { name: "Kharagpur", latitude: "", longitude: "" },
  { name: "Haldia", latitude: "", longitude: "" },
  { name: "Bardhaman", latitude: "", longitude: "" },
  { name: "Malda", latitude: "", longitude: "" },
  { name: "Baharampur", latitude: "", longitude: "" },
  { name: "Jalpaiguri", latitude: "", longitude: "" },
  { name: "Raiganj", latitude: "", longitude: "" },
  { name: "Balurghat", latitude: "", longitude: "" },
  { name: "Purulia", latitude: "", longitude: "" },
  { name: "Bankura", latitude: "", longitude: "" },
  { name: "Cooch Behar", latitude: "", longitude: "" },
  { name: "Alipurduar", latitude: "", longitude: "" },
  { name: "Darjeeling", latitude: "", longitude: "" },
  { name: "Kalimpong", latitude: "", longitude: "" },
  { name: "Ranchi", latitude: "", longitude: "" },
  { name: "Jamshedpur", latitude: "", longitude: "" },
  { name: "Dhanbad", latitude: "", longitude: "" },
  { name: "Bokaro", latitude: "", longitude: "" },
  { name: "Deoghar", latitude: "", longitude: "" },
  { name: "Hazaribagh", latitude: "", longitude: "" },
  { name: "Giridih", latitude: "", longitude: "" },
  { name: "Ramgarh", latitude: "", longitude: "" },
  { name: "Medininagar", latitude: "", longitude: "" },
  { name: "Phusro", latitude: "", longitude: "" },
  { name: "Dumka", latitude: "", longitude: "" },
  { name: "Chaibasa", latitude: "", longitude: "" },
  { name: "Sahibganj", latitude: "", longitude: "" },
  { name: "Gumla", latitude: "", longitude: "" },
  { name: "Lohardaga", latitude: "", longitude: "" },
  { name: "Patna", latitude: "", longitude: "" },
  { name: "Gaya", latitude: "", longitude: "" },
  { name: "Muzaffarpur", latitude: "", longitude: "" },
  { name: "Darbhanga", latitude: "", longitude: "" },
  { name: "Bhagalpur", latitude: "", longitude: "" },
  { name: "Bihar Sharif", latitude: "", longitude: "" },
  { name: "Arrah", latitude: "", longitude: "" },
  { name: "Begusarai", latitude: "", longitude: "" },
  { name: "Katihar", latitude: "", longitude: "" },
  { name: "Chhapra", latitude: "", longitude: "" },
  { name: "Purnia", latitude: "", longitude: "" },
  { name: "Samastipur", latitude: "", longitude: "" },
  { name: "Sitamarhi", latitude: "", longitude: "" },
  { name: "Hajipur", latitude: "", longitude: "" },
  { name: "Aurangabad", latitude: "", longitude: "" },
  { name: "Bettiah", latitude: "", longitude: "" },
  { name: "Motihari", latitude: "", longitude: "" },
  { name: "Sasaram", latitude: "", longitude: "" },
  { name: "Dehri", latitude: "", longitude: "" },
  { name: "Siwan", latitude: "", longitude: "" },
  { name: "Jehanabad", latitude: "", longitude: "" },
  { name: "Nawada", latitude: "", longitude: "" },
  { name: "Bagaha", latitude: "", longitude: "" },
  { name: "Kishanganj", latitude: "", longitude: "" },
  { name: "Guwahati", latitude: "", longitude: "" },
  { name: "Dispur", latitude: "", longitude: "" },
  { name: "Shillong", latitude: "", longitude: "" },
  { name: "Imphal", latitude: "", longitude: "" },
  { name: "Aizawl", latitude: "", longitude: "" },
  { name: "Kohima", latitude: "", longitude: "" },
  { name: "Dimapur", latitude: "", longitude: "" },
  { name: "Itanagar", latitude: "", longitude: "" },
  { name: "Naharlagun", latitude: "", longitude: "" },
  { name: "Agartala", latitude: "", longitude: "" },
  { name: "Gangtok", latitude: "", longitude: "" },
  { name: "Silchar", latitude: "", longitude: "" },
  { name: "Dibrugarh", latitude: "", longitude: "" },
  { name: "Jorhat", latitude: "", longitude: "" },
  { name: "Tezpur", latitude: "", longitude: "" },
  { name: "Nagaon", latitude: "", longitude: "" },
  { name: "Tinsukia", latitude: "", longitude: "" },
  { name: "Sivasagar", latitude: "", longitude: "" },
  { name: "Thiruvananthapuram", latitude: "", longitude: "" },
  { name: "Trivandrum", latitude: "", longitude: "" },
  { name: "Kochi", latitude: "", longitude: "" },
  { name: "Cochin", latitude: "", longitude: "" },
  { name: "Kozhikode", latitude: "", longitude: "" },
  { name: "Calicut", latitude: "", longitude: "" },
  { name: "Thrissur", latitude: "", longitude: "" },
  { name: "Trichur", latitude: "", longitude: "" },
  { name: "Kollam", latitude: "", longitude: "" },
  { name: "Quilon", latitude: "", longitude: "" },
  { name: "Alappuzha", latitude: "", longitude: "" },
  { name: "Alleppey", latitude: "", longitude: "" },
  { name: "Palakkad", latitude: "", longitude: "" },
  { name: "Kottayam", latitude: "", longitude: "" },
  { name: "Malappuram", latitude: "", longitude: "" },
  { name: "Kannur", latitude: "", longitude: "" },
  { name: "Kasaragod", latitude: "", longitude: "" },
  { name: "Idukki", latitude: "", longitude: "" },
  { name: "Wayanad", latitude: "", longitude: "" },
  { name: "Pathanamthitta", latitude: "", longitude: "" },
  { name: "Ernakulam", latitude: "", longitude: "" },
  { name: "Angamaly", latitude: "", longitude: "" },
  { name: "Perumbavoor", latitude: "", longitude: "" },
  { name: "Muvattupuzha", latitude: "", longitude: "" },
  { name: "Coimbatore", latitude: "", longitude: "" },
  { name: "Madurai", latitude: "", longitude: "" },
  { name: "Tiruchirappalli", latitude: "", longitude: "" },
  { name: "Trichy", latitude: "", longitude: "" },
  { name: "Salem", latitude: "", longitude: "" },
  { name: "Tiruppur", latitude: "", longitude: "" },
  { name: "Erode", latitude: "", longitude: "" },
  { name: "Tirunelveli", latitude: "", longitude: "" },
  { name: "Vellore", latitude: "", longitude: "" },
  { name: "Thoothukudi", latitude: "", longitude: "" },
  { name: "Tuticorin", latitude: "", longitude: "" },
  { name: "Dindigul", latitude: "", longitude: "" },
  { name: "Thanjavur", latitude: "", longitude: "" },
  { name: "Ranipet", latitude: "", longitude: "" },
  { name: "Sivakasi", latitude: "", longitude: "" },
  { name: "Karur", latitude: "", longitude: "" },
  { name: "Ooty", latitude: "", longitude: "" },
  { name: "Udhagamandalam", latitude: "", longitude: "" },
  { name: "Kanchipuram", latitude: "", longitude: "" },
  { name: "Kumbakonam", latitude: "", longitude: "" },
  { name: "Nagercoil", latitude: "", longitude: "" },
  { name: "Hosur", latitude: "", longitude: "" },
  { name: "Krishnagiri", latitude: "", longitude: "" },
  { name: "Dharmapuri", latitude: "", longitude: "" },
  { name: "Namakkal", latitude: "", longitude: "" },
  { name: "Perambalur", latitude: "", longitude: "" },
  { name: "Ariyalur", latitude: "", longitude: "" },
  { name: "Cuddalore", latitude: "", longitude: "" },
  { name: "Villupuram", latitude: "", longitude: "" },
  { name: "Tiruvannamalai", latitude: "", longitude: "" },
  { name: "Pudukkottai", latitude: "", longitude: "" },
  { name: "Ramanathapuram", latitude: "", longitude: "" },
  { name: "Virudhunagar", latitude: "", longitude: "" },
  { name: "Theni", latitude: "", longitude: "" },
  { name: "Nilgiris", latitude: "", longitude: "" },
  { name: "Mysore", latitude: "", longitude: "" },
  { name: "Mysuru", latitude: "", longitude: "" },
  { name: "Mangalore", latitude: "", longitude: "" },
  { name: "Mangaluru", latitude: "", longitude: "" },
  { name: "Hubli", latitude: "", longitude: "" },
  { name: "Hubballi", latitude: "", longitude: "" },
  { name: "Dharwad", latitude: "", longitude: "" },
  { name: "Belgaum", latitude: "", longitude: "" },
  { name: "Belagavi", latitude: "", longitude: "" },
  { name: "Gulbarga", latitude: "", longitude: "" },
  { name: "Kalaburagi", latitude: "", longitude: "" },
  { name: "Davanagere", latitude: "", longitude: "" },
  { name: "Bellary", latitude: "", longitude: "" },
  { name: "Ballari", latitude: "", longitude: "" },
  { name: "Bijapur", latitude: "", longitude: "" },
  { name: "Vijayapura", latitude: "", longitude: "" },
  { name: "Shimoga", latitude: "", longitude: "" },
  { name: "Shivamogga", latitude: "", longitude: "" },
  { name: "Tumkur", latitude: "", longitude: "" },
  { name: "Tumakuru", latitude: "", longitude: "" },
  { name: "Udupi", latitude: "", longitude: "" },
  { name: "Manipal", latitude: "", longitude: "" },
  { name: "Hassan", latitude: "", longitude: "" },
  { name: "Mandya", latitude: "", longitude: "" },
  { name: "Chikmagalur", latitude: "", longitude: "" },
  { name: "Chikkamagaluru", latitude: "", longitude: "" },
  { name: "Raichur", latitude: "", longitude: "" },
  { name: "Bidar", latitude: "", longitude: "" },
  { name: "Bagalkot", latitude: "", longitude: "" },
  { name: "Haveri", latitude: "", longitude: "" },
  { name: "Gadag", latitude: "", longitude: "" },
  { name: "Koppal", latitude: "", longitude: "" },
  { name: "Yadgir", latitude: "", longitude: "" },
  { name: "Chamarajanagar", latitude: "", longitude: "" },
  { name: "Kodagu", latitude: "", longitude: "" },
  { name: "Coorg", latitude: "", longitude: "" },
  { name: "Ramanagara", latitude: "", longitude: "" },
  { name: "Chikkaballapur", latitude: "", longitude: "" },
  { name: "Kolar", latitude: "", longitude: "" },
  { name: "Chitradurga", latitude: "", longitude: "" },
  { name: "Visakhapatnam", latitude: "", longitude: "" },
  { name: "Vijayawada", latitude: "", longitude: "" },
  { name: "Guntur", latitude: "", longitude: "" },
  { name: "Nellore", latitude: "", longitude: "" },
  { name: "Kurnool", latitude: "", longitude: "" },
  { name: "Rajahmundry", latitude: "", longitude: "" },
  { name: "Tirupati", latitude: "", longitude: "" },
  { name: "Kakinada", latitude: "", longitude: "" },
  { name: "Kadapa", latitude: "", longitude: "" },
  { name: "Anantapur", latitude: "", longitude: "" },
  { name: "Vizianagaram", latitude: "", longitude: "" },
  { name: "Eluru", latitude: "", longitude: "" },
  { name: "Ongole", latitude: "", longitude: "" },
  { name: "Nandyal", latitude: "", longitude: "" },
  { name: "Machilipatnam", latitude: "", longitude: "" },
  { name: "Tenali", latitude: "", longitude: "" },
  { name: "Chittoor", latitude: "", longitude: "" },
  { name: "Hindupur", latitude: "", longitude: "" },
  { name: "Proddatur", latitude: "", longitude: "" },
  { name: "Adoni", latitude: "", longitude: "" },
  { name: "Madanapalle", latitude: "", longitude: "" },
  { name: "Tadepalligudem", latitude: "", longitude: "" },
  { name: "Chirala", latitude: "", longitude: "" },
  { name: "Srikakulam", latitude: "", longitude: "" },
  { name: "Bhimavaram", latitude: "", longitude: "" },
  { name: "Gudivada", latitude: "", longitude: "" },
  { name: "Narasaraopet", latitude: "", longitude: "" },
  { name: "Tadipatri", latitude: "", longitude: "" },
  { name: "Warangal", latitude: "", longitude: "" },
  { name: "Karimnagar", latitude: "", longitude: "" },
  { name: "Nizamabad", latitude: "", longitude: "" },
  { name: "Khammam", latitude: "", longitude: "" },
  { name: "Mahbubnagar", latitude: "", longitude: "" },
  { name: "Nalgonda", latitude: "", longitude: "" },
  { name: "Adilabad", latitude: "", longitude: "" },
  { name: "Ramagundam", latitude: "", longitude: "" },
  { name: "Suryapet", latitude: "", longitude: "" },
  { name: "Miryalaguda", latitude: "", longitude: "" },
  { name: "Jagtial", latitude: "", longitude: "" },
  { name: "Mancherial", latitude: "", longitude: "" },
  { name: "Nirmal", latitude: "", longitude: "" },
  { name: "Nagpur", latitude: "", longitude: "" },
  { name: "Nashik", latitude: "", longitude: "" },
  { name: "Sambhaji Nagar", latitude: "", longitude: "" },
  { name: "Solapur", latitude: "", longitude: "" },
  { name: "Amravati", latitude: "", longitude: "" },
  { name: "Nanded", latitude: "", longitude: "" },
  { name: "Kolhapur", latitude: "", longitude: "" },
  { name: "Sangli", latitude: "", longitude: "" },
  { name: "Satara", latitude: "", longitude: "" },
  { name: "Latur", latitude: "", longitude: "" },
  { name: "Ahmednagar", latitude: "", longitude: "" },
  { name: "Jalgaon", latitude: "", longitude: "" },
  { name: "Akola", latitude: "", longitude: "" },
  { name: "Dhule", latitude: "", longitude: "" },
  { name: "Jalna", latitude: "", longitude: "" },
  { name: "Chandrapur", latitude: "", longitude: "" },
  { name: "Parbhani", latitude: "", longitude: "" },
  { name: "Yavatmal", latitude: "", longitude: "" },
  { name: "Wardha", latitude: "", longitude: "" },
  { name: "Gondia", latitude: "", longitude: "" },
  { name: "Bhandara", latitude: "", longitude: "" },
  { name: "Washim", latitude: "", longitude: "" },
  { name: "Hingoli", latitude: "", longitude: "" },
  { name: "Buldhana", latitude: "", longitude: "" },
  { name: "Osmanabad", latitude: "", longitude: "" },
  { name: "Beed", latitude: "", longitude: "" },
  { name: "Ratnagiri", latitude: "", longitude: "" },
  { name: "Sindhudurg", latitude: "", longitude: "" },
  { name: "Sangamner", latitude: "", longitude: "" },
  { name: "Shirdi", latitude: "", longitude: "" },
  { name: "Igatpuri", latitude: "", longitude: "" },
  { name: "Matheran", latitude: "", longitude: "" },
  { name: "Lonavala", latitude: "", longitude: "" },
  { name: "Khandala", latitude: "", longitude: "" },
  { name: "Mahabaleshwar", latitude: "", longitude: "" },
  { name: "Panchgani", latitude: "", longitude: "" },
  { name: "Alibaug", latitude: "", longitude: "" },
  { name: "Raigad", latitude: "", longitude: "" },
  { name: "Murud", latitude: "", longitude: "" },
  { name: "Roha", latitude: "", longitude: "" },
  { name: "Pen", latitude: "", longitude: "" },
  { name: "Uran", latitude: "", longitude: "" },
  { name: "Karjat", latitude: "", longitude: "" },
  { name: "Khopoli", latitude: "", longitude: "" },
  { name: "Neral", latitude: "", longitude: "" },
  { name: "Panaji", latitude: "", longitude: "" },
  { name: "Margao", latitude: "", longitude: "" },
  { name: "Madgaon", latitude: "", longitude: "" },
  { name: "Vasco da Gama", latitude: "", longitude: "" },
  { name: "Ponda", latitude: "", longitude: "" },
  { name: "Mapusa", latitude: "", longitude: "" },
  { name: "Bicholim", latitude: "", longitude: "" },
  { name: "Curchorem", latitude: "", longitude: "" },
  { name: "Sanquelim", latitude: "", longitude: "" },
  { name: "Cuncolim", latitude: "", longitude: "" },
  { name: "Valpoi", latitude: "", longitude: "" },
  { name: "Canacona", latitude: "", longitude: "" },
  { name: "Sanguem", latitude: "", longitude: "" },
  { name: "Quepem", latitude: "", longitude: "" },
  { name: "Pernem", latitude: "", longitude: "" },
  { name: "Srinagar", latitude: "", longitude: "" },
  { name: "Jammu", latitude: "", longitude: "" },
  { name: "Anantnag", latitude: "", longitude: "" },
  { name: "Baramulla", latitude: "", longitude: "" },
  { name: "Sopore", latitude: "", longitude: "" },
  { name: "Pulwama", latitude: "", longitude: "" },
  { name: "Budgam", latitude: "", longitude: "" },
  { name: "Poonch", latitude: "", longitude: "" },
  { name: "Kathua", latitude: "", longitude: "" },
  { name: "Udhampur", latitude: "", longitude: "" },
  { name: "Rajouri", latitude: "", longitude: "" },
  { name: "Kupwara", latitude: "", longitude: "" },
  { name: "Leh", latitude: "", longitude: "" },
  { name: "Kargil", latitude: "", longitude: "" },
];

export const CITIES: string[] = CITY_DETAILS.map((city) => city.name);
